package com.hatio.CurrencyConverterAPIIntegration.service;

import com.hatio.CurrencyConverterAPIIntegration.repository.CurrencyConverterRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.ResourceAccessException;
import org.springframework.web.client.RestTemplate;

import java.util.HashMap;
import java.util.Map;


@Service
public class CurrencyConverterService implements CurrencyConverterRepository {

    @Autowired
    private RestTemplate restTemplate;


    //Here I used final and private because this url is fixed and generated by exchange rates api so i don't want to edit it and make it private to avoid using form other packages

    private final String API_URL = "http://api.exchangeratesapi.io/v1/latest?access_key=ba517c540d5b47bbf4d13f422fccda52";

    @Override
    public Map<String, Object> getConvertedRates(String base) {


        try{
            ResponseEntity<Map> response = restTemplate.getForEntity(API_URL, Map.class);
            Map<String, Object> responseBody = response.getBody();

            if (responseBody == null || !responseBody.containsKey("rates")) {
                throw new RuntimeException("Failed to fetch exchange rates.");
            }

            //Here i am giving the base value present in request
            responseBody.put("base", base);

            // Exchange api by default giving rates based on EUR (EUR-based)
            Map<String, Object> ratesObject = (Map<String, Object>) responseBody.get("rates");

            // Converting rates to <String, Double> for easy calculations
            Map<String, Double> rates = new HashMap<>();
            for (Map.Entry<String, Object> entry : ratesObject.entrySet()) {
                rates.put(entry.getKey(), ((Number) entry.getValue()).doubleValue());
            }

            // Finding conversion rate for the new base currency
            double baseRate = rates.get(base);

            // Converting all rates relative to the new base currency
            Map<String, Double> newRates = new HashMap<>();
            for (Map.Entry<String, Double> entry : rates.entrySet()) {
                newRates.put(entry.getKey(), entry.getValue() / baseRate);
            }

            // newResponse is the actual response which has base as requested base
            Map<String, Object> newResponse = new HashMap<>();
            newResponse.put("base", base);
            newResponse.put("rates", newRates);

            return newResponse;
        }catch (HttpClientErrorException e) {
            // Handling the HTTP errors where Unauthorized,  Not Found
            throw new RuntimeException("API request failed: " + e.getStatusCode() + " - " + e.getResponseBodyAsString());

        } catch (ResourceAccessException e) {
            // Handleling network issues where timeout, connection failure
            throw new RuntimeException("Failed to connect to the API: " + e.getMessage());

        }catch (RuntimeException e){
            //If response body is null it will return the error message
            throw new RuntimeException(e.getMessage());
        }
        catch (Exception e) {
            // Handling any other unexpected errors
            throw new RuntimeException("Unexpected error: " + e.getMessage());
        }
    }

    @Override
    public Map<String, Object> getRequiredConvertedRates(Map<String, Object> requestBody) {
        try {
            String fromCurrency = (String) requestBody.get("from");
            String toCurrency = (String) requestBody.get("to");
            double amount = ((Number) requestBody.get("amount")).doubleValue();

            // Fetching current rates from above method the api base currency is EUR so i give EUR here to avoid extra calculations
            Map<String, Object> exchangeRates = getConvertedRates("EUR");

            if (exchangeRates == null || !exchangeRates.containsKey("rates")) {
                throw new RuntimeException("Failed to fetch exchange rates.");
            }

            Map<String, Double> rates = (Map<String, Double>) exchangeRates.get("rates");

            //Here i am taking the currency what is requested in post method
            if (!rates.containsKey(fromCurrency) || !rates.containsKey(toCurrency)) {
                throw new IllegalArgumentException("Invalid currency code: " + fromCurrency + " or " + toCurrency);
            }

            // Converting amount
            double fromRate = rates.get(fromCurrency);
            double toRate = rates.get(toCurrency);
            double convertedAmount = (amount / fromRate) * toRate;

            // Building response
            Map<String, Object> response = new HashMap<>();
            response.put("from", fromCurrency);
            response.put("to", toCurrency);
            response.put("amount", amount);
            response.put("convertedAmount", convertedAmount);

            return response;

        } catch (Exception e) {
            //when we call the above method the api calling is already done by that method that's why i redure catch blocks
            throw new RuntimeException("Error processing conversion: " + e.getMessage());
        }
    }
}
